[build]
  command = "nuxt prepare && npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[images.remote_patterns]]
  protocol = "https"
  hostname = "images.microcms-assets.io"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
